#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : poetry-core
Version  : 1.0.7
Release  : 1
URL      : https://files.pythonhosted.org/packages/40/d0/adc9ab25f68d9382f32c355627423a32135efaa5aaeebd6dec6d19e6b0af/poetry-core-1.0.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/40/d0/adc9ab25f68d9382f32c355627423a32135efaa5aaeebd6dec6d19e6b0af/poetry-core-1.0.7.tar.gz
Summary  : Poetry PEP 517 Build Backend
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause MIT
Requires: poetry-core-license = %{version}-%{release}
Requires: poetry-core-python = %{version}-%{release}
Requires: poetry-core-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Poetry Core
[![PyPI version](https://img.shields.io/pypi/v/poetry-core)](https://pypi.org/project/poetry-core/)
[![Python Versions](https://img.shields.io/pypi/pyversions/poetry-core)](https://pypi.org/project/poetry-core/)
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
[![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black)
[![](https://github.com/python-poetry/poetry-core/workflows/Tests/badge.svg)](https://github.com/python-poetry/poetry-core/actions?query=workflow%3ATests)

%package license
Summary: license components for the poetry-core package.
Group: Default

%description license
license components for the poetry-core package.


%package python
Summary: python components for the poetry-core package.
Group: Default
Requires: poetry-core-python3 = %{version}-%{release}

%description python
python components for the poetry-core package.


%package python3
Summary: python3 components for the poetry-core package.
Group: Default
Requires: python3-core
Provides: pypi(poetry_core)

%description python3
python3 components for the poetry-core package.


%prep
%setup -q -n poetry-core-1.0.7
cd %{_builddir}/poetry-core-1.0.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637086896
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/poetry-core
cp %{_builddir}/poetry-core-1.0.7/poetry/core/_vendor/packaging/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/poetry-core/bd0b945d001aebc12dd7cdbf100427f1bc8d6957
cp %{_builddir}/poetry-core-1.0.7/poetry/core/_vendor/packaging/LICENSE.BSD %{buildroot}/usr/share/package-licenses/poetry-core/0156fc44e9a92e871fe58d650b392df3fc7c2dc3
cp %{_builddir}/poetry-core-1.0.7/poetry/core/_vendor/pyparsing.LICENSE %{buildroot}/usr/share/package-licenses/poetry-core/1d5d84d6fe1c735c23a6cb2449d5dd5353d778a5
cp %{_builddir}/poetry-core-1.0.7/poetry/core/_vendor/six.LICENSE %{buildroot}/usr/share/package-licenses/poetry-core/5aa89b53a6e35810f63b69d01b463ef3c6576853
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/poetry-core/0156fc44e9a92e871fe58d650b392df3fc7c2dc3
/usr/share/package-licenses/poetry-core/1d5d84d6fe1c735c23a6cb2449d5dd5353d778a5
/usr/share/package-licenses/poetry-core/5aa89b53a6e35810f63b69d01b463ef3c6576853
/usr/share/package-licenses/poetry-core/bd0b945d001aebc12dd7cdbf100427f1bc8d6957

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
